{% set version = "2.3.0" %}

package:
  name: libhdfs3
  version: "{{ version }}"

source:
  url: https://github.com/martindurant/libhdfs3-downstream/archive/{{ version }}.tar.gz
  sha256: 5a31e866332fedd645aeffea970588fb1d260440c0cd07fedced05b9f8e403d3
  patches:
      - CMakeLists.txt.diff

build:
  number: 4
  # This package is a dependency of hdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - libgsasl 1.8.*
    - libntlm
    - libprotobuf
    - libuuid
    - libxml2
    - krb5
  run:
    - boost-cpp
    - libgsasl 1.8.*
    - libntlm
    - libprotobuf
    - libuuid
    - libxml2
    - krb5
    - curl

test:
  commands:
    - test -f $PREFIX/lib/libhdfs3${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/PivotalRD/libhdfs3
  license: Apache 2.0
  license_file: LICENSE
  summary: A Native C/C++ HDFS Client

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mrocklin
