{% set version = "2.3" %}

package:
  name: libhdfs3
  version: "{{ version }}"

source:
#  fn: libhdfs3-{{ version }}.tar.gz
#  url: https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/archive/v{{ version }}.tar.gz
#  sha256: b68d112a3c234a50f646071b1de07e5e191018f6762492cd04d57390e1fd5a16
  git_url: https://github.com/martindurant/libhdfs3-downstream.git
  patches:
      - CMakeLists.txt.diff

build:
  number: 1
  # This package is a dependency of hdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]

requirements:
  build:
    - cmake
    - boost-cpp 1.66.0
    - libgsasl 1.8.*
    - libntlm
    - libprotobuf 3.5.*
    - libuuid
    - libxml2 2.9.*
    - krb5 1.14.*
  run:
    - boost-cpp 1.66.0
    - libgsasl 1.8.*
    - libntlm
    - libprotobuf 3.5.*
    - libuuid
    - libxml2 2.9.*
    - krb5 1.14.*
    - curl

test:
  commands:
    - test -f $PREFIX/lib/libhdfs3.so  # [linux]
    - test -f $PREFIX/lib/libhdfs3.dylib  # [osx]

about:
  home: https://github.com/PivotalRD/libhdfs3
  license: Apache 2.0
  summary: A Native C/C++ HDFS Client

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mrocklin
