travis:
  secure:
    BINSTAR_TOKEN: PXPxnmyy1kgChZjm/uiS3E/SW2+QUxE9hIDosIX/TyZFkjvRW+M7tIwt9D0/gVoy92n2/nvrYS0JBCq0Q0t6hiDv4Bb1yhR+ckDjpP7b48VNcF0GeisPtbPym5WRHSFCKLh9vpfHyXiw97RQdpF8n1eQBiaRs2cTyrU1if3D6Ai0EnQXINOca6nY+q6jFnmykp4PCg9X+10KM7sW6cNLFt5yEVC+15cqMsHs5xck7x/ax3Soy3RsOKQQ2SgFvbz/zey4B1pQ7dH4cvzIKoWHEO+X+gVC3biSlMx5Qdu1R9h29IkAmiHlv0mdrvhep5UCubRKGF2IjuxNagSdKJD/vz4y2+2Fn86YuawbQ/xham6KKgI6GDI/U+vN/yeYV/CF1hlH4pjm5VPRkaDFMffK73CEax4vFn0ap9NpmeAuuvfc3Cjxo+LcUYLGn8YRNKGKssy+zQ0dpMVmYxd2ZPuq0OjMAvL80ymMRwA8+0hScKVj427moAybNBOPFfEU/I0FOux0+QfLRzhksRbQ0q92uUg3JPvttcrurb/rtThQCCRT3ymkaLERgoBwJ/H0u/Ek++ZO/AYgKEBtsXltcsX3EzYmKLPGhX02YQDa8SzJgUZ/pHj8UJcSeL9orYlWe2OIvxC+PaCNZ1pkhtw0atHZwwI+aP05o+SlKJU3xSPl70E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
